version: '3.7'
services:
  # server:
  #   build: 
  #     context: .
  #     dockerfile: ./image/server/Dockerfile
  #   environment:
  #     EULA: "true"
  #     UID: ${EUID:-1000}
  #     GID: ${EGID:-1000}
  #   ports:
  #     - "${SERVER_PORT:-25565}:25565"
  #   volumes:
  #     - ./plugins:/plugins

  compile:
    build: 
      context: .
      dockerfile: ./image/compile/Dockerfile
    environment:
      UID: ${EUID:-1000}
      GID: ${EGID:-1000}
    volumes:
      - ./pom.xml:/workspace/pom.xml
      - ./src:/workspace/src
      - ./target:/workspace/target
    tty: true

