name: GlobalStorage
version: '${project.version}'
main: com.motsuni.globalstorage.GlobalStorage
api-version: '1.20'
commands:
  globalstorage:
    description: Get interface of GlobalStorage
    usage: /globalstorage <give | inventory <open [page] | save | sort [asc | desc]> >
    aliases:
      - gs
