name: GlobalStorage
version: '${project.version}'
main: com.motsuni.globalstorage.GlobalStorage
api-version: '1.20'
commands:
  globalinventory:
    description: Get interface of GlobalStorage
    usage: /globalinventory <give | inventory <open [page] | save | clear> >
    aliases:
      - gi
